name: "Update and build packages, and populate cache"
on:
  pull_request:
  push:
  schedule:
    - cron:  '50 6 * * *'
jobs:
  build:
    environment:
      name: cachix
    strategy:
      matrix:
        nurRepo:
          - ivar
        cachixName:
          - ivar
        nixPath:
          - nixpkgs=channel:nixpkgs-unstable
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2.3.4
    - name: Install nix
      uses: cachix/install-nix-action@v12
      with:
        nix_path: "${{ matrix.nixPath }}"
    - name: Show nixpkgs version
      run: nix-instantiate --eval -E '(import <nixpkgs> {}).lib.version'
    - name: Setup cachix
      uses: cachix/cachix-action@v8
      if: ${{ matrix.cachixName != '<YOUR_CACHIX_NAME>' }}
      with:
        name: ${{ matrix.cachixName }}
        signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
    - name: Update packages
      run: |
        cd ryujinx
        ./updater.sh
        cd ../yuzu
        ./updater.sh
    - name: Push changes
      uses: actions-x/commit@v2
      with:
        message: Updated package set
        files: ryujinx
    - name: Build nix packages
      run: nix run -I 'nixpkgs=channel:nixpkgs-unstable' nixpkgs.nix-build-uncached -c nix-build-uncached ci.nix -A cacheOutputs
    - name: Trigger NUR update
      if: ${{ matrix.nurRepo != '<YOUR_REPO_NAME>' }}
      run: curl -XPOST "https://nur-update.herokuapp.com/update?repo=${{ matrix.nurRepo }}"
